# Netlify configuration file

[build]
  # Directory to publish
  publish = "dist"
  # Build command
  command = "npm run build"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"